name: CI Test

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install black flake8 isort mypy

      - name: Run black
        run: black --check .

      - name: Run flake8
        run: flake8 .

      - name: Run isort
        run: isort --check-only .

      - name: Run mypy
        run: mypy .

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: lint  # Запускаем тесты только после успешного линтинга
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest


